### ISSUE TITLE
unknown field "futureRetentionPeriodNanos" in namespace.RetentionOptions

### ISSUE THREAD

**Issue by jadencodes** [m3db/m3db-operator#128]
Thanks for opening an issue for the M3DB Operator! We'd love to help you, but we need the following information included
with any issue:

* What version of Kubernetes are you running? Please include the output of `kubectl version`.
Client Version: 1.14
Server Version: 1.11

* What are you trying to do?
Deploy the operator with a specific configuration with the options from: https://operator.m3db.io/api/#retentionoptions

* What did you expect to happen?
An operator to be deployed with the following configuration:

```yaml
apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: m3db-cluster
spec:
  image: quay.io/m3db/m3dbnode:latest
  replicationFactor: 1
  numberOfShards: 256
  isolationGroups:
    - name: us-west-2b
      numInstances: 3
  namespaces:
    - name: default
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        repairEnabled: false
        snapshotEnabled: true
        retentionOptions:
          retentionPeriod: 720h
          blockSize: 90m
          bufferFuture: 20m
          bufferPast: 1h
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriod: 5m
        indexOptions:
          enabled: true
          blockSize: 3h
  etcdEndpoints:
    - http://etcd-0.etcd:2379
    - http://etcd-1.etcd:2379
    - http://etcd-2.etcd:2379
  podIdentityConfig:
    sources:
      - PodUID
  containerResources:
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 12Gi
      cpu: 4
```
* What happened?

The operator seems to recognize the cluster and it's pods, however it throws this error : 
```console
controller.go:297] error syncing cluster 'm3dbtest/m3db-cluster': unknown field "futureRetentionPeriodNanos" in namespace.RetentionOptions
```
In addition (but unsure if this is related). When prometheus is trying to write to the cluster, it throws this error:
```console
failed to meet consistency level majority with 0/1 success, 1 nodes responded, errors: [shard 102 in host {\"name\":\"m3db-cluster-rep0-2\",\"uid\":\"45db2e75-66b8-11e9-86c9-0225ab994878\"} is not available (initializing)]
```

I assume the latter error is due to the namespace not being initialized fully but wanted to include it in case it helps.

Thank you for any help!

**Comment by schallert** [comment]
Hey @jadencodes,

Thanks for your detailed issue! I think a few things are going on here.

The `futureRetentionPeriodNanos` field was added to M3DB in https://github.com/m3db/m3/pull/1083. Prior to https://github.com/m3db/m3db-operator/pull/117, which is not yet in a release (but is on `:master`), we used Protobuf's default of strict unmarshalling. So when the operator is getting the namespace back from M3DB it can't unmarshal the protobuf without that change. If you use the `:master` tag of the operator, or wait until 0.2 you should be set.

With regards to your consistency failure, I have two recommendations.

1. I don't think it's safe to have M3DB clusters with RF=1, as if you lose a single node you'll never be able to recover it.

2. I'd recommend using persistent storage with `podIdentityConfig.sources: []` (this will be the default in a future release). When running with no PV's and `PodUID` as a source, if one pod restarts and a second from another replica set restarts before it finishes bootstrapping the cluster will be in a stuck state, as nodes can't quorum bootstrap for all shards.

I think some of these issues will be solved when we implement stricter cluster validation (#124), as we could warn users when the have unsafe cluster configs and maybe have a flag to force creation of a potentially unsafe cluster, acknowledging the risks.

Can you try using `:master` of the operator with PVs and see how your cluster performs? With `:master` of the operator you can create RF=3 zonal clusters with a isogroup config such as 
```
  isolationGroups:
  - name: us-west1-b-1
    numInstances: 3
    nodeAffinityValues:
    - us-west1-b
  - name: us-west1-b-2
    numInstances: 3
    nodeAffinityValues:
    - us-west1-b
  - name: us-west1-b-3
    numInstances: 3
    nodeAffinityValues:
    - us-west1-b
```

Let me know if this solves your problem, and feel free to ping me any time in our [Gitter](https://gitter.im/m3db/kubernetes) room!
