### ISSUE TITLE
Custom namespace config is ignored

### ISSUE THREAD

**Issue by marcoabreu** [m3db/m3db-operator#130]
* What version of the operator are you running?
```
    Image:         quay.io/m3db/m3db-operator:v0.1.4
    Image ID:      docker-pullable://quay.io/m3db/m3db-operator@sha256:f0e48c78b3563bbd03570ef56d4d711b071f48701864cc0dc65992ce1d169ca2
```

* What version of Kubernetes are you running?
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-19T22:13:37Z", GoVersion:"go1.12.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

* What are you trying to do?
I'm trying to define custom namespaces through the following example config. Please excuse it being that long, but I have created multiple namespaces in case a certain config-style or naming would be causing the issue:
```
apiVersion: operator.m3db.io/v1alpha1
kind: M3DBCluster
metadata:
  name: simple-cluster
spec:
  image: quay.io/m3db/m3dbnode:v0.8.4
  replicationFactor: 3
  numberOfShards: 256
  etcdEndpoints:
  - http://etcd-0.etcd:2379
  - http://etcd-1.etcd:2379
  - http://etcd-2.etcd:2379
  isolationGroups:
    - name: us-west-2a
      numInstances: 1
    - name: us-west-2b
      numInstances: 1
    - name: us-west-2d
      numInstances: 1
  podIdentityConfig:
    sources:
      - PodUID
  namespaces:
    - name: tiger
      preset: 10s:2d
    - name: default
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
          retentionPeriodDuration: 720h
          blockSizeDuration: 12h
          bufferFutureDuration: 1h
          bufferPastDuration: 1h
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriodDuration: 5m
        indexOptions:
          enabled: true
          blockSizeDuration: 12h
    - name: elephant
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
          retentionPeriodDuration: 720h
          blockSizeDuration: 12h
          bufferFutureDuration: 1h
          bufferPastDuration: 1h
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriodDuration: 5m
        indexOptions:
          enabled: true
          blockSizeDuration: 12h
```

* What did you expect to happen?
After running ``kubectl apply -f m3db-simple-cluster.yml``, I would expect these namespaces to show up when I run ``kubectl logs simple-cluster-rep0-0``.

* What happened?
``kubectl logs simple-cluster-rep0-0`` returned the following log.
```
{"level":"info","ts":1556542510.8016489,"msg":"initial namespace value received"}
{"level":"info","ts":1556542510.8017457,"msg":"resolving namespaces with namespace watch"}
{"level":"info","ts":1556542510.801812,"msg":"updating database namespaces","adds":"[metrics-10s:2d]","updates":"[]","schema updates":"[]","removals":"[]"}
{"level":"info","ts":1556542511.1120646,"msg":"node tchannelthrift: listening","address":"0.0.0.0:9000"}
{"level":"info","ts":1556542511.1121905,"msg":"cluster tchannelthrift: listening","address":"0.0.0.0:9001"}
{"level":"info","ts":1556542511.1124318,"msg":"node httpjson: listening","address":"0.0.0.0:9002"}
{"level":"info","ts":1556542511.11253,"msg":"cluster httpjson: listening","address":"0.0.0.0:9003"}
{"level":"info","ts":1556542511.113027,"msg":"bootstrap finished","namespace":"metrics-10s:2d","duration":0.000006162}
```
This indicates that the example namespace ``metrics-10s:2d`` is being created and my custom config is ignored.

At first I though that I might have done something wrong with my config, so I started to insert spelling-errors into the namespace-config - they were entirely ignored. To ensure that my config is actually picked up, I changed ``  image: quay.io/m3db/m3dbnode:v0.8.4`` to something different and it was properly picked up. Thus, I come to the conclusion that the entire namespace field is being ignored.

I also tried to re-deploy the operator in the following fashion, but it made no difference:
```
helm del --purge m3db-operator
kubectl delete -f m3db-simple-cluster.yml
helm install m3db/m3db-operator --namespace m3db-operator --name m3db-operator
kubectl apply -f m3db-simple-cluster.yml
```

The lack of the namespace "default" that I'm using in conjunction with Prometheus causes the following log-spam:
```
2019-04-29T13:07:10.441Z	ERROR	Write error	{"err": "failed to meet consistency level majority with 0/3 success, 3 nodes responded, errors: [error writing to host {\"name\":\"simple-cluster-rep0-0\",\"uid\":\"2f30a5d8-669b-11e9-a89b-0e86e7b0d9a0\"}: tchannel error ErrCodeUnexpected: Error({Type:BAD_REQUEST Message:unknown namespace: default}) error writing to host {\"name\":\"simple-cluster-rep2-0\",\"uid\":\"458f9b02-669b-11e9-a89b-0e86e7b0d9a0\"}: tchannel error ErrCodeUnexpected: Error({Type:BAD_REQUEST Message:unknown namespace: default}) error writing to host {\"name\":\"simple-cluster-rep1-0\",\"uid\":\"3c178ab9-669b-11e9-a89b-0e86e7b0d9a0\"}: tchannel error ErrCodeUnexpected: Error({Type:BAD_REQUEST Message:unknown namespace: default})]"}
```
