### ISSUE TITLE
Can't specify pod annotations

### ISSUE THREAD

**Issue by brndnmtthws** [m3db/m3db-operator#136]
There's no way to add annotations to m3db pods at the moment. Specifically, I want to add these:

```yaml
   annotations:
     prometheus.io/scrape: "true"
     prometheus.io/port: "7203"
```

Ideally it could be part of the cluster spec.
