### ISSUE TITLE
Error when creating custom namespace

### ISSUE THREAD

**Issue by araigneeman** [m3db/m3db-operator#161]
Thanks for opening an issue for the M3DB Operator! We'd love to help you, but we need the following information included
with any issue:

* What version of the operator are you running? Please include the docker tag. If using `master`, please include the git
  SHA logged when the operator first starts.

v0.2.0

* What version of Kubernetes are you running? Please include the output of `kubectl version`.

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

* What are you trying to do?

Create a custom namespace

* What did you expect to happen?

Operator create the namespace

* What happened?

The following error:
`{"level":"info","ts":1562666576.3649237,"msg":"Event(v1.ObjectReference{Kind:\"M3DBCluster\", Namespace:\"monitoring\", Name:\"prometheus-m3db\", UID:\"c08baeb8-a22f-11e9-aaa7-005056b89351\", APIVersion:\"operator.m3db.io/v1alpha1\", ResourceVersion:\"6194864\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedToCreate' failed to create namespace: error forming request for namespace 'metrics-24h': time: invalid duration ","controller":"m3db-cluster-controller"}`

And that's my namespace spec in the cluster yaml:

```
  namespaces:
    - name: metrics-24h
      options:
        bootstrapEnabled: true
        flushEnabled: true
        writesToCommitLog: true
        cleanupEnabled: true
        snapshotEnabled: true
        repairEnabled: false
        retentionOptions:
          retentionPeriodDuration: 24h
          blockSizeDuration: 1h
          bufferFutureDuration: 10m
          bufferPastDuration: 10m
          blockDataExpiry: true
          blockDataExpiryAfterNotAccessPeriodDuration: 5m
        indexOptions:
          enabled: true
          blockSizeDuration: 1h
```
I tried with different configurations but i always get the same error when creating the namespace.
