### ISSUE TITLE
Updates to M3DBCluster spec are not applied to pods

### ISSUE THREAD

**Issue by shoopdedoop** [m3db/m3db-operator#226]
Operator version: docker tag v0.8.0
k8s version: v1.15.7

I am attempting to update the memory limits on an existing cluster.  I would have thought that updating M3DBCluster spec would have updated the pods.  Even after manually deleting a pod it does not pick up the new limits.

STR:
1) Deploy a cluster with limits cpu or memory and allow it to bootstrap
2) Update the M3DBCluster spec with new cpu or memory limits
3) Observe the new limits are not applied and the pods are not restarted
4) Attempt to manually delete a pod and observe even then the new limits are not applied

Example:

```
kubectl get pods -n testns m3db-cluster-pv-rep0-0 -o yaml

    resources:
      limits:
        memory: 50Gi
      requests:
        memory: 50Gi
```
Cluster definition shows the following

```
kubectl get M3DBCluster -n testns -o yaml

  spec:
    annotations:
      metricsPath: /metrics
      metricsPort: 7203,9004
      rootPath: /
    configMapName: m3db-configmap-db
    containerResources:
      limits:
        memory: 90Gi
      requests:
        memory: 90Gi
```

Pod limits are not updated.  Only after deleting and recreating the cluster were the limits updated.
